fix set/getrlimit build
Hi Adhemerval, with my recent patch to kernel, getrlimit and setrlimit
syscalls are deprecated for new architectures, and partially for
aarch64/ilp32. The patch is acked by arch maintainers, and most probably
will be submitted soon.

https://patchwork.kernel.org/patch/9390685/

With it, and with recent get/setrlimit rework, glibc fails the build:
make -C ilp32.build -j`nproc`  > ../ilp32.build.log;
../sysdeps/unix/sysv/linux/getrlimit64.c: In function ‘__getrlimit64’:
../sysdeps/unix/sysv/linux/getrlimit64.c:55:246: error: ‘__NR_getrlimit’ undeclared (first use in this function)
../sysdeps/unix/sysv/linux/getrlimit64.c:55:246: note: each undeclared identifier is reported only once for each function it appears in
../sysdeps/unix/sysv/linux/getrlimit64.c: In function ‘__getrlimit64’:
../sysdeps/unix/sysv/linux/getrlimit64.c:55:246: error: ‘__NR_getrlimit’ undeclared (first use in this function)
../sysdeps/unix/sysv/linux/getrlimit64.c:55:246: note: each undeclared identifier is reported only once for each function it appears in

This fixes the problem. Could you incorporate it to set/getrlimit patch?